Document: miind
Title: Debian miind Manual
Author: <insert document author here>
Abstract: This manual describes what miind is
 and how it can be used to
 manage online manuals on Debian systems.
Section: unknown

Format: debiandoc-sgml
Files: /usr/share/doc/miind/miind.sgml.gz

Format: postscript
Files: /usr/share/doc/miind/miind.ps.gz

Format: text
Files: /usr/share/doc/miind/miind.text.gz

Format: HTML
Index: /usr/share/doc/miind/html/index.html
Files: /usr/share/doc/miind/html/*.html
