set(VCPKG_TARGET_ARCHITECTURE x64)
set(VCPKG_CRT_LINKAGE dynamic)
set(VCPKG_LIBRARY_LINKAGE static)

set(VCPKG_CMAKE_SYSTEM_NAME Linux)

if(PORT STREQUAL "boost")
    set(VCPKG_LIBRARY_LINKAGE dynamic)
endif()
if(PORT STREQUAL "freeglut")
    set(VCPKG_LIBRARY_LINKAGE dynamic)
endif()
if(PORT STREQUAL "glew")
    set(VCPKG_LIBRARY_LINKAGE dynamic)
endif()
