//
// File generated by rootcint at Mon Jul 25 20:50:47 2011

// Do NOT change. Changes will be lost next time file is generated
//

#define R__DICTIONARY_FILENAME dict
#include "RConfig.h" //rootcint 4834
#if !defined(R__ACCESS_IN_SYMBOL)
//Break the privacy of classes -- Disabled for the moment
#define private public
#define protected public
#endif

// Since CINT ignores the std namespace, we need to do so in this file.
namespace std {} using namespace std;
#include "dict.h"

#include "TCollectionProxyInfo.h"
#include "TClass.h"
#include "TBuffer.h"
#include "TMemberInspector.h"
#include "TError.h"

#ifndef G__ROOT
#define G__ROOT
#endif

#include "RtypesImp.h"
#include "TIsAProxy.h"

// START OF SHADOWS

namespace ROOT {
   namespace Shadow {
   } // of namespace Shadow
} // of namespace ROOT
// END OF SHADOWS

namespace ROOT {
   void ClamLibcLcLRootLayerDescription_ShowMembers(void *obj, TMemberInspector &R__insp);
   static void *new_ClamLibcLcLRootLayerDescription(void *p = 0);
   static void *newArray_ClamLibcLcLRootLayerDescription(Long_t size, void *p);
   static void delete_ClamLibcLcLRootLayerDescription(void *p);
   static void deleteArray_ClamLibcLcLRootLayerDescription(void *p);
   static void destruct_ClamLibcLcLRootLayerDescription(void *p);

   // Function generating the singleton type initializer
   static TGenericClassInfo *GenerateInitInstanceLocal(const ::ClamLib::RootLayerDescription*)
   {
      ::ClamLib::RootLayerDescription *ptr = 0;
      static ::TVirtualIsAProxy* isa_proxy = new ::TInstrumentedIsAProxy< ::ClamLib::RootLayerDescription >(0);
      static ::ROOT::TGenericClassInfo 
         instance("ClamLib::RootLayerDescription", ::ClamLib::RootLayerDescription::Class_Version(), "./../../libs/ClamLib/RootLayerDescription.h", 28,
                  typeid(::ClamLib::RootLayerDescription), DefineBehavior(ptr, ptr),
                  &::ClamLib::RootLayerDescription::Dictionary, isa_proxy, 4,
                  sizeof(::ClamLib::RootLayerDescription) );
      instance.SetNew(&new_ClamLibcLcLRootLayerDescription);
      instance.SetNewArray(&newArray_ClamLibcLcLRootLayerDescription);
      instance.SetDelete(&delete_ClamLibcLcLRootLayerDescription);
      instance.SetDeleteArray(&deleteArray_ClamLibcLcLRootLayerDescription);
      instance.SetDestructor(&destruct_ClamLibcLcLRootLayerDescription);
      return &instance;
   }
   TGenericClassInfo *GenerateInitInstance(const ::ClamLib::RootLayerDescription*)
   {
      return GenerateInitInstanceLocal((::ClamLib::RootLayerDescription*)0);
   }
   // Static variable to force the class initialization
   static ::ROOT::TGenericClassInfo *_R__UNIQUE_(Init) = GenerateInitInstanceLocal((const ::ClamLib::RootLayerDescription*)0x0); R__UseDummy(_R__UNIQUE_(Init));
} // end of namespace ROOT

      namespace ClamLib {
//______________________________________________________________________________
TClass *RootLayerDescription::fgIsA = 0;  // static to hold class pointer

//______________________________________________________________________________
const char *RootLayerDescription::Class_Name()
{
   return "ClamLib::RootLayerDescription";
}

//______________________________________________________________________________
const char *RootLayerDescription::ImplFileName()
{
   return ::ROOT::GenerateInitInstanceLocal((const ::ClamLib::RootLayerDescription*)0x0)->GetImplFileName();
}

//______________________________________________________________________________
int RootLayerDescription::ImplFileLine()
{
   return ::ROOT::GenerateInitInstanceLocal((const ::ClamLib::RootLayerDescription*)0x0)->GetImplFileLine();
}

//______________________________________________________________________________
void RootLayerDescription::Dictionary()
{
   fgIsA = ::ROOT::GenerateInitInstanceLocal((const ::ClamLib::RootLayerDescription*)0x0)->GetClass();
}

//______________________________________________________________________________
TClass *RootLayerDescription::Class()
{
   if (!fgIsA) fgIsA = ::ROOT::GenerateInitInstanceLocal((const ::ClamLib::RootLayerDescription*)0x0)->GetClass();
   return fgIsA;
}

} // namespace ClamLib
      namespace ClamLib {
//______________________________________________________________________________
void RootLayerDescription::Streamer(TBuffer &R__b)
{
   // Stream an object of class ClamLib::RootLayerDescription.

   if (R__b.IsReading()) {
      R__b.ReadClassBuffer(ClamLib::RootLayerDescription::Class(),this);
   } else {
      R__b.WriteClassBuffer(ClamLib::RootLayerDescription::Class(),this);
   }
}

} // namespace ClamLib
//______________________________________________________________________________
      namespace ClamLib {
void RootLayerDescription::ShowMembers(TMemberInspector &R__insp)
{
      // Inspect the data members of an object of class ClamLib::RootLayerDescription.
      typedef ::ClamLib::RootLayerDescription msvc_bug_workaround;
      TClass *R__cl = msvc_bug_workaround::IsA();
      if (R__cl || R__insp.IsA()) { }
      R__insp.Inspect(R__cl, R__insp.GetParent(), "_nr_x_pixels", &_nr_x_pixels);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "_nr_y_pixels", &_nr_y_pixels);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "_nr_features", &_nr_features);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "_size_receptive_field_x", &_size_receptive_field_x);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "_size_receptive_field_y", &_size_receptive_field_y);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "_nr_x_skips", &_nr_x_skips);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "_nr_y_skips", &_nr_y_skips);
      TNamed::ShowMembers(R__insp);
}

} // namespace ClamLib
namespace ROOT {
   // Wrappers around operator new
   static void *new_ClamLibcLcLRootLayerDescription(void *p) {
      return  p ? new(p) ::ClamLib::RootLayerDescription : new ::ClamLib::RootLayerDescription;
   }
   static void *newArray_ClamLibcLcLRootLayerDescription(Long_t nElements, void *p) {
      return p ? new(p) ::ClamLib::RootLayerDescription[nElements] : new ::ClamLib::RootLayerDescription[nElements];
   }
   // Wrapper around operator delete
   static void delete_ClamLibcLcLRootLayerDescription(void *p) {
      delete ((::ClamLib::RootLayerDescription*)p);
   }
   static void deleteArray_ClamLibcLcLRootLayerDescription(void *p) {
      delete [] ((::ClamLib::RootLayerDescription*)p);
   }
   static void destruct_ClamLibcLcLRootLayerDescription(void *p) {
      typedef ::ClamLib::RootLayerDescription current_t;
      ((current_t*)p)->~current_t();
   }
} // end of namespace ROOT for class ::ClamLib::RootLayerDescription

namespace ROOT {
   void vectorlEClamLibcLcLRootLayerDescriptiongR_ShowMembers(void *obj, TMemberInspector &R__insp);
   static void vectorlEClamLibcLcLRootLayerDescriptiongR_Dictionary();
   static void *new_vectorlEClamLibcLcLRootLayerDescriptiongR(void *p = 0);
   static void *newArray_vectorlEClamLibcLcLRootLayerDescriptiongR(Long_t size, void *p);
   static void delete_vectorlEClamLibcLcLRootLayerDescriptiongR(void *p);
   static void deleteArray_vectorlEClamLibcLcLRootLayerDescriptiongR(void *p);
   static void destruct_vectorlEClamLibcLcLRootLayerDescriptiongR(void *p);

   // Function generating the singleton type initializer
   static TGenericClassInfo *GenerateInitInstanceLocal(const vector<ClamLib::RootLayerDescription>*)
   {
      vector<ClamLib::RootLayerDescription> *ptr = 0;
      static ::TVirtualIsAProxy* isa_proxy = new ::TIsAProxy(typeid(vector<ClamLib::RootLayerDescription>),0);
      static ::ROOT::TGenericClassInfo 
         instance("vector<ClamLib::RootLayerDescription>", -2, "prec_stl/vector", 49,
                  typeid(vector<ClamLib::RootLayerDescription>), DefineBehavior(ptr, ptr),
                  0, &vectorlEClamLibcLcLRootLayerDescriptiongR_Dictionary, isa_proxy, 4,
                  sizeof(vector<ClamLib::RootLayerDescription>) );
      instance.SetNew(&new_vectorlEClamLibcLcLRootLayerDescriptiongR);
      instance.SetNewArray(&newArray_vectorlEClamLibcLcLRootLayerDescriptiongR);
      instance.SetDelete(&delete_vectorlEClamLibcLcLRootLayerDescriptiongR);
      instance.SetDeleteArray(&deleteArray_vectorlEClamLibcLcLRootLayerDescriptiongR);
      instance.SetDestructor(&destruct_vectorlEClamLibcLcLRootLayerDescriptiongR);
      instance.AdoptCollectionProxyInfo(TCollectionProxyInfo::Generate(TCollectionProxyInfo::Pushback< vector<ClamLib::RootLayerDescription> >()));
      return &instance;
   }
   // Static variable to force the class initialization
   static ::ROOT::TGenericClassInfo *_R__UNIQUE_(Init) = GenerateInitInstanceLocal((const vector<ClamLib::RootLayerDescription>*)0x0); R__UseDummy(_R__UNIQUE_(Init));

   // Dictionary for non-ClassDef classes
   static void vectorlEClamLibcLcLRootLayerDescriptiongR_Dictionary() {
      ::ROOT::GenerateInitInstanceLocal((const vector<ClamLib::RootLayerDescription>*)0x0)->GetClass();
   }

} // end of namespace ROOT

namespace ROOT {
   // Wrappers around operator new
   static void *new_vectorlEClamLibcLcLRootLayerDescriptiongR(void *p) {
      return  p ? ::new((::ROOT::TOperatorNewHelper*)p) vector<ClamLib::RootLayerDescription> : new vector<ClamLib::RootLayerDescription>;
   }
   static void *newArray_vectorlEClamLibcLcLRootLayerDescriptiongR(Long_t nElements, void *p) {
      return p ? ::new((::ROOT::TOperatorNewHelper*)p) vector<ClamLib::RootLayerDescription>[nElements] : new vector<ClamLib::RootLayerDescription>[nElements];
   }
   // Wrapper around operator delete
   static void delete_vectorlEClamLibcLcLRootLayerDescriptiongR(void *p) {
      delete ((vector<ClamLib::RootLayerDescription>*)p);
   }
   static void deleteArray_vectorlEClamLibcLcLRootLayerDescriptiongR(void *p) {
      delete [] ((vector<ClamLib::RootLayerDescription>*)p);
   }
   static void destruct_vectorlEClamLibcLcLRootLayerDescriptiongR(void *p) {
      typedef vector<ClamLib::RootLayerDescription> current_t;
      ((current_t*)p)->~current_t();
   }
} // end of namespace ROOT for class vector<ClamLib::RootLayerDescription>

/********************************************************
* dict.cxx
* CAUTION: DON'T CHANGE THIS FILE. THIS FILE IS AUTOMATICALLY GENERATED
*          FROM HEADER FILES LISTED IN G__setup_cpp_environmentXXX().
*          CHANGE THOSE HEADER FILES AND REGENERATE THIS FILE.
********************************************************/

#ifdef G__MEMTEST
#undef malloc
#undef free
#endif

extern "C" void G__cpp_reset_tagtabledict();

extern "C" void G__set_cpp_environmentdict() {
  G__add_compiledheader("TObject.h");
  G__add_compiledheader("TMemberInspector.h");
  G__add_compiledheader("../../libs/ClamLib/RootLayeredNetDescription.h");
  G__cpp_reset_tagtabledict();
}
#include <new>
extern "C" int G__cpp_dllrevdict() { return(30051515); }

/*********************************************************
* Member function Interface Method
*********************************************************/

/* ClamLib::RootLayerDescription */
static int G__dict_269_0_1(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
   ClamLib::RootLayerDescription* p = NULL;
   char* gvp = (char*) G__getgvp();
   int n = G__getaryconstruct();
   if (n) {
     if ((gvp == (char*)G__PVOID) || (gvp == 0)) {
       p = new ClamLib::RootLayerDescription[n];
     } else {
       p = new((void*) gvp) ClamLib::RootLayerDescription[n];
     }
   } else {
     if ((gvp == (char*)G__PVOID) || (gvp == 0)) {
       p = new ClamLib::RootLayerDescription;
     } else {
       p = new((void*) gvp) ClamLib::RootLayerDescription;
     }
   }
   result7->obj.i = (long) p;
   result7->ref = (long) p;
   G__set_tagnum(result7,G__get_linked_tagnum(&G__dictLN_ClamLibcLcLRootLayerDescription));
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__dict_269_0_2(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letint(result7, 85, (long) ClamLib::RootLayerDescription::Class());
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__dict_269_0_3(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letint(result7, 67, (long) ClamLib::RootLayerDescription::Class_Name());
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__dict_269_0_4(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letint(result7, 115, (long) ClamLib::RootLayerDescription::Class_Version());
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__dict_269_0_5(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      ClamLib::RootLayerDescription::Dictionary();
      G__setnull(result7);
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__dict_269_0_9(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      ((ClamLib::RootLayerDescription*) G__getstructoffset())->StreamerNVirtual(*(TBuffer*) libp->para[0].ref);
      G__setnull(result7);
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__dict_269_0_10(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letint(result7, 67, (long) ClamLib::RootLayerDescription::DeclFileName());
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__dict_269_0_11(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letint(result7, 105, (long) ClamLib::RootLayerDescription::ImplFileLine());
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__dict_269_0_12(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letint(result7, 67, (long) ClamLib::RootLayerDescription::ImplFileName());
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__dict_269_0_13(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letint(result7, 105, (long) ClamLib::RootLayerDescription::DeclFileLine());
   return(1 || funcname || hash || result7 || libp) ;
}

// automatic copy constructor
static int G__dict_269_0_14(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)

{
   ClamLib::RootLayerDescription* p;
   void* tmp = (void*) G__int(libp->para[0]);
   p = new ClamLib::RootLayerDescription(*(ClamLib::RootLayerDescription*) tmp);
   result7->obj.i = (long) p;
   result7->ref = (long) p;
   G__set_tagnum(result7,G__get_linked_tagnum(&G__dictLN_ClamLibcLcLRootLayerDescription));
   return(1 || funcname || hash || result7 || libp) ;
}

// automatic destructor
typedef ClamLib::RootLayerDescription G__TClamLibcLcLRootLayerDescription;
static int G__dict_269_0_15(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
   char* gvp = (char*) G__getgvp();
   long soff = G__getstructoffset();
   int n = G__getaryconstruct();
   //
   //has_a_delete: 1
   //has_own_delete1arg: 0
   //has_own_delete2arg: 0
   //
   if (!soff) {
     return(1);
   }
   if (n) {
     if (gvp == (char*)G__PVOID) {
       delete[] (ClamLib::RootLayerDescription*) soff;
     } else {
       G__setgvp((long) G__PVOID);
       for (int i = n - 1; i >= 0; --i) {
         ((ClamLib::RootLayerDescription*) (soff+(sizeof(ClamLib::RootLayerDescription)*i)))->~G__TClamLibcLcLRootLayerDescription();
       }
       G__setgvp((long)gvp);
     }
   } else {
     if (gvp == (char*)G__PVOID) {
       delete (ClamLib::RootLayerDescription*) soff;
     } else {
       G__setgvp((long) G__PVOID);
       ((ClamLib::RootLayerDescription*) (soff))->~G__TClamLibcLcLRootLayerDescription();
       G__setgvp((long)gvp);
     }
   }
   G__setnull(result7);
   return(1 || funcname || hash || result7 || libp) ;
}

// automatic assignment operator
static int G__dict_269_0_16(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
   ClamLib::RootLayerDescription* dest = (ClamLib::RootLayerDescription*) G__getstructoffset();
   *dest = *(ClamLib::RootLayerDescription*) libp->para[0].ref;
   const ClamLib::RootLayerDescription& obj = *dest;
   result7->ref = (long) (&obj);
   result7->obj.i = (long) (&obj);
   return(1 || funcname || hash || result7 || libp) ;
}


/* vector<ClamLib::RootLayerDescription,allocator<ClamLib::RootLayerDescription> > */
static int G__dict_272_0_1(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      {
         const ClamLib::RootLayerDescription& obj = ((vector<ClamLib::RootLayerDescription,allocator<ClamLib::RootLayerDescription> >*) G__getstructoffset())->at((vector<ClamLib::RootLayerDescription,allocator<ClamLib::RootLayerDescription> >::size_type) G__int(libp->para[0]));
         result7->ref = (long) (&obj);
         result7->obj.i = (long) (&obj);
      }
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__dict_272_0_2(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      {
         vector<ClamLib::RootLayerDescription,allocator<ClamLib::RootLayerDescription> >::iterator* pobj;
         vector<ClamLib::RootLayerDescription,allocator<ClamLib::RootLayerDescription> >::iterator xobj = ((vector<ClamLib::RootLayerDescription,allocator<ClamLib::RootLayerDescription> >*) G__getstructoffset())->begin();
         pobj = new vector<ClamLib::RootLayerDescription,allocator<ClamLib::RootLayerDescription> >::iterator(xobj);
         result7->obj.i = (long) ((void*) pobj);
         result7->ref = result7->obj.i;
         G__store_tempobject(*result7);
      }
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__dict_272_0_3(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      {
         vector<ClamLib::RootLayerDescription,allocator<ClamLib::RootLayerDescription> >::iterator* pobj;
         vector<ClamLib::RootLayerDescription,allocator<ClamLib::RootLayerDescription> >::iterator xobj = ((vector<ClamLib::RootLayerDescription,allocator<ClamLib::RootLayerDescription> >*) G__getstructoffset())->end();
         pobj = new vector<ClamLib::RootLayerDescription,allocator<ClamLib::RootLayerDescription> >::iterator(xobj);
         result7->obj.i = (long) ((void*) pobj);
         result7->ref = result7->obj.i;
         G__store_tempobject(*result7);
      }
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__dict_272_0_4(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      {
         vector<ClamLib::RootLayerDescription,allocator<ClamLib::RootLayerDescription> >::reverse_iterator* pobj;
         vector<ClamLib::RootLayerDescription,allocator<ClamLib::RootLayerDescription> >::reverse_iterator xobj = ((vector<ClamLib::RootLayerDescription,allocator<ClamLib::RootLayerDescription> >*) G__getstructoffset())->rbegin();
         pobj = new vector<ClamLib::RootLayerDescription,allocator<ClamLib::RootLayerDescription> >::reverse_iterator(xobj);
         result7->obj.i = (long) ((void*) pobj);
         result7->ref = result7->obj.i;
         G__store_tempobject(*result7);
      }
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__dict_272_0_5(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      {
         vector<ClamLib::RootLayerDescription,allocator<ClamLib::RootLayerDescription> >::reverse_iterator* pobj;
         vector<ClamLib::RootLayerDescription,allocator<ClamLib::RootLayerDescription> >::reverse_iterator xobj = ((vector<ClamLib::RootLayerDescription,allocator<ClamLib::RootLayerDescription> >*) G__getstructoffset())->rend();
         pobj = new vector<ClamLib::RootLayerDescription,allocator<ClamLib::RootLayerDescription> >::reverse_iterator(xobj);
         result7->obj.i = (long) ((void*) pobj);
         result7->ref = result7->obj.i;
         G__store_tempobject(*result7);
      }
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__dict_272_0_6(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letint(result7, 104, (long) ((const vector<ClamLib::RootLayerDescription,allocator<ClamLib::RootLayerDescription> >*) G__getstructoffset())->size());
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__dict_272_0_7(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letint(result7, 104, (long) ((const vector<ClamLib::RootLayerDescription,allocator<ClamLib::RootLayerDescription> >*) G__getstructoffset())->max_size());
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__dict_272_0_8(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      ((vector<ClamLib::RootLayerDescription,allocator<ClamLib::RootLayerDescription> >*) G__getstructoffset())->resize((vector<ClamLib::RootLayerDescription,allocator<ClamLib::RootLayerDescription> >::size_type) G__int(libp->para[0]));
      G__setnull(result7);
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__dict_272_0_9(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      ((vector<ClamLib::RootLayerDescription,allocator<ClamLib::RootLayerDescription> >*) G__getstructoffset())->resize((vector<ClamLib::RootLayerDescription,allocator<ClamLib::RootLayerDescription> >::size_type) G__int(libp->para[0]), *((ClamLib::RootLayerDescription*) G__int(libp->para[1])));
      G__setnull(result7);
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__dict_272_0_10(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letint(result7, 104, (long) ((const vector<ClamLib::RootLayerDescription,allocator<ClamLib::RootLayerDescription> >*) G__getstructoffset())->capacity());
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__dict_272_0_11(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letint(result7, 103, (long) ((const vector<ClamLib::RootLayerDescription,allocator<ClamLib::RootLayerDescription> >*) G__getstructoffset())->empty());
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__dict_272_0_12(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      {
         const ClamLib::RootLayerDescription& obj = ((vector<ClamLib::RootLayerDescription,allocator<ClamLib::RootLayerDescription> >*) G__getstructoffset())->operator[]((vector<ClamLib::RootLayerDescription,allocator<ClamLib::RootLayerDescription> >::size_type) G__int(libp->para[0]));
         result7->ref = (long) (&obj);
         result7->obj.i = (long) (&obj);
      }
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__dict_272_0_13(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
   vector<ClamLib::RootLayerDescription,allocator<ClamLib::RootLayerDescription> >* p = NULL;
   char* gvp = (char*) G__getgvp();
   int n = G__getaryconstruct();
   if (n) {
     if ((gvp == (char*)G__PVOID) || (gvp == 0)) {
       p = new vector<ClamLib::RootLayerDescription,allocator<ClamLib::RootLayerDescription> >[n];
     } else {
       p = new((void*) gvp) vector<ClamLib::RootLayerDescription,allocator<ClamLib::RootLayerDescription> >[n];
     }
   } else {
     if ((gvp == (char*)G__PVOID) || (gvp == 0)) {
       p = new vector<ClamLib::RootLayerDescription,allocator<ClamLib::RootLayerDescription> >;
     } else {
       p = new((void*) gvp) vector<ClamLib::RootLayerDescription,allocator<ClamLib::RootLayerDescription> >;
     }
   }
   result7->obj.i = (long) p;
   result7->ref = (long) p;
   G__set_tagnum(result7,G__get_linked_tagnum(&G__dictLN_vectorlEClamLibcLcLRootLayerDescriptioncOallocatorlEClamLibcLcLRootLayerDescriptiongRsPgR));
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__dict_272_0_14(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
   vector<ClamLib::RootLayerDescription,allocator<ClamLib::RootLayerDescription> >* p = NULL;
   char* gvp = (char*) G__getgvp();
   switch (libp->paran) {
   case 2:
     //m: 2
     if ((gvp == (char*)G__PVOID) || (gvp == 0)) {
       p = new vector<ClamLib::RootLayerDescription,allocator<ClamLib::RootLayerDescription> >((vector<ClamLib::RootLayerDescription,allocator<ClamLib::RootLayerDescription> >::size_type) G__int(libp->para[0]), *(ClamLib::RootLayerDescription*) libp->para[1].ref);
     } else {
       p = new((void*) gvp) vector<ClamLib::RootLayerDescription,allocator<ClamLib::RootLayerDescription> >((vector<ClamLib::RootLayerDescription,allocator<ClamLib::RootLayerDescription> >::size_type) G__int(libp->para[0]), *(ClamLib::RootLayerDescription*) libp->para[1].ref);
     }
     break;
   case 1:
     //m: 1
     if ((gvp == (char*)G__PVOID) || (gvp == 0)) {
       p = new vector<ClamLib::RootLayerDescription,allocator<ClamLib::RootLayerDescription> >((vector<ClamLib::RootLayerDescription,allocator<ClamLib::RootLayerDescription> >::size_type) G__int(libp->para[0]));
     } else {
       p = new((void*) gvp) vector<ClamLib::RootLayerDescription,allocator<ClamLib::RootLayerDescription> >((vector<ClamLib::RootLayerDescription,allocator<ClamLib::RootLayerDescription> >::size_type) G__int(libp->para[0]));
     }
     break;
   }
   result7->obj.i = (long) p;
   result7->ref = (long) p;
   G__set_tagnum(result7,G__get_linked_tagnum(&G__dictLN_vectorlEClamLibcLcLRootLayerDescriptioncOallocatorlEClamLibcLcLRootLayerDescriptiongRsPgR));
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__dict_272_0_15(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
   vector<ClamLib::RootLayerDescription,allocator<ClamLib::RootLayerDescription> >* p = NULL;
   char* gvp = (char*) G__getgvp();
   //m: 1
   if ((gvp == (char*)G__PVOID) || (gvp == 0)) {
     p = new vector<ClamLib::RootLayerDescription,allocator<ClamLib::RootLayerDescription> >(*(vector<ClamLib::RootLayerDescription,allocator<ClamLib::RootLayerDescription> >*) libp->para[0].ref);
   } else {
     p = new((void*) gvp) vector<ClamLib::RootLayerDescription,allocator<ClamLib::RootLayerDescription> >(*(vector<ClamLib::RootLayerDescription,allocator<ClamLib::RootLayerDescription> >*) libp->para[0].ref);
   }
   result7->obj.i = (long) p;
   result7->ref = (long) p;
   G__set_tagnum(result7,G__get_linked_tagnum(&G__dictLN_vectorlEClamLibcLcLRootLayerDescriptioncOallocatorlEClamLibcLcLRootLayerDescriptiongRsPgR));
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__dict_272_0_16(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
   vector<ClamLib::RootLayerDescription,allocator<ClamLib::RootLayerDescription> >* p = NULL;
   char* gvp = (char*) G__getgvp();
   //m: 2
   if ((gvp == (char*)G__PVOID) || (gvp == 0)) {
     p = new vector<ClamLib::RootLayerDescription,allocator<ClamLib::RootLayerDescription> >(*((vector<ClamLib::RootLayerDescription,allocator<ClamLib::RootLayerDescription> >::const_iterator*) G__int(libp->para[0])), *((vector<ClamLib::RootLayerDescription,allocator<ClamLib::RootLayerDescription> >::const_iterator*) G__int(libp->para[1])));
   } else {
     p = new((void*) gvp) vector<ClamLib::RootLayerDescription,allocator<ClamLib::RootLayerDescription> >(*((vector<ClamLib::RootLayerDescription,allocator<ClamLib::RootLayerDescription> >::const_iterator*) G__int(libp->para[0])), *((vector<ClamLib::RootLayerDescription,allocator<ClamLib::RootLayerDescription> >::const_iterator*) G__int(libp->para[1])));
   }
   result7->obj.i = (long) p;
   result7->ref = (long) p;
   G__set_tagnum(result7,G__get_linked_tagnum(&G__dictLN_vectorlEClamLibcLcLRootLayerDescriptioncOallocatorlEClamLibcLcLRootLayerDescriptiongRsPgR));
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__dict_272_0_17(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      {
         const vector<ClamLib::RootLayerDescription,allocator<ClamLib::RootLayerDescription> >& obj = ((vector<ClamLib::RootLayerDescription,allocator<ClamLib::RootLayerDescription> >*) G__getstructoffset())->operator=(*(vector<ClamLib::RootLayerDescription,allocator<ClamLib::RootLayerDescription> >*) libp->para[0].ref);
         result7->ref = (long) (&obj);
         result7->obj.i = (long) (&obj);
      }
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__dict_272_0_18(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      ((vector<ClamLib::RootLayerDescription,allocator<ClamLib::RootLayerDescription> >*) G__getstructoffset())->reserve((vector<ClamLib::RootLayerDescription,allocator<ClamLib::RootLayerDescription> >::size_type) G__int(libp->para[0]));
      G__setnull(result7);
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__dict_272_0_19(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      {
         const ClamLib::RootLayerDescription& obj = ((vector<ClamLib::RootLayerDescription,allocator<ClamLib::RootLayerDescription> >*) G__getstructoffset())->front();
         result7->ref = (long) (&obj);
         result7->obj.i = (long) (&obj);
      }
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__dict_272_0_20(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      {
         const ClamLib::RootLayerDescription& obj = ((vector<ClamLib::RootLayerDescription,allocator<ClamLib::RootLayerDescription> >*) G__getstructoffset())->back();
         result7->ref = (long) (&obj);
         result7->obj.i = (long) (&obj);
      }
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__dict_272_0_21(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      ((vector<ClamLib::RootLayerDescription,allocator<ClamLib::RootLayerDescription> >*) G__getstructoffset())->push_back(*(ClamLib::RootLayerDescription*) libp->para[0].ref);
      G__setnull(result7);
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__dict_272_0_22(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      ((vector<ClamLib::RootLayerDescription,allocator<ClamLib::RootLayerDescription> >*) G__getstructoffset())->swap(*(vector<ClamLib::RootLayerDescription,allocator<ClamLib::RootLayerDescription> >*) libp->para[0].ref);
      G__setnull(result7);
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__dict_272_0_23(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      {
         vector<ClamLib::RootLayerDescription,allocator<ClamLib::RootLayerDescription> >::iterator* pobj;
         vector<ClamLib::RootLayerDescription,allocator<ClamLib::RootLayerDescription> >::iterator xobj = ((vector<ClamLib::RootLayerDescription,allocator<ClamLib::RootLayerDescription> >*) G__getstructoffset())->insert(*((vector<ClamLib::RootLayerDescription,allocator<ClamLib::RootLayerDescription> >::iterator*) G__int(libp->para[0])), *(ClamLib::RootLayerDescription*) libp->para[1].ref);
         pobj = new vector<ClamLib::RootLayerDescription,allocator<ClamLib::RootLayerDescription> >::iterator(xobj);
         result7->obj.i = (long) ((void*) pobj);
         result7->ref = result7->obj.i;
         G__store_tempobject(*result7);
      }
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__dict_272_0_24(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      ((vector<ClamLib::RootLayerDescription,allocator<ClamLib::RootLayerDescription> >*) G__getstructoffset())->insert(*((vector<ClamLib::RootLayerDescription,allocator<ClamLib::RootLayerDescription> >::iterator*) G__int(libp->para[0])), *((vector<ClamLib::RootLayerDescription,allocator<ClamLib::RootLayerDescription> >::const_iterator*) G__int(libp->para[1]))
, *((vector<ClamLib::RootLayerDescription,allocator<ClamLib::RootLayerDescription> >::const_iterator*) G__int(libp->para[2])));
      G__setnull(result7);
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__dict_272_0_25(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      ((vector<ClamLib::RootLayerDescription,allocator<ClamLib::RootLayerDescription> >*) G__getstructoffset())->insert(*((vector<ClamLib::RootLayerDescription,allocator<ClamLib::RootLayerDescription> >::iterator*) G__int(libp->para[0])), (vector<ClamLib::RootLayerDescription,allocator<ClamLib::RootLayerDescription> >::size_type) G__int(libp->para[1])
, *(ClamLib::RootLayerDescription*) libp->para[2].ref);
      G__setnull(result7);
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__dict_272_0_26(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      ((vector<ClamLib::RootLayerDescription,allocator<ClamLib::RootLayerDescription> >*) G__getstructoffset())->pop_back();
      G__setnull(result7);
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__dict_272_0_27(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      ((vector<ClamLib::RootLayerDescription,allocator<ClamLib::RootLayerDescription> >*) G__getstructoffset())->erase(*((vector<ClamLib::RootLayerDescription,allocator<ClamLib::RootLayerDescription> >::iterator*) G__int(libp->para[0])));
      G__setnull(result7);
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__dict_272_0_28(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      ((vector<ClamLib::RootLayerDescription,allocator<ClamLib::RootLayerDescription> >*) G__getstructoffset())->erase(*((vector<ClamLib::RootLayerDescription,allocator<ClamLib::RootLayerDescription> >::iterator*) G__int(libp->para[0])), *((vector<ClamLib::RootLayerDescription,allocator<ClamLib::RootLayerDescription> >::iterator*) G__int(libp->para[1])));
      G__setnull(result7);
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__dict_272_0_29(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      ((vector<ClamLib::RootLayerDescription,allocator<ClamLib::RootLayerDescription> >*) G__getstructoffset())->clear();
      G__setnull(result7);
   return(1 || funcname || hash || result7 || libp) ;
}

// automatic destructor
typedef vector<ClamLib::RootLayerDescription,allocator<ClamLib::RootLayerDescription> > G__TvectorlEClamLibcLcLRootLayerDescriptioncOallocatorlEClamLibcLcLRootLayerDescriptiongRsPgR;
static int G__dict_272_0_30(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
   char* gvp = (char*) G__getgvp();
   long soff = G__getstructoffset();
   int n = G__getaryconstruct();
   //
   //has_a_delete: 0
   //has_own_delete1arg: 0
   //has_own_delete2arg: 0
   //
   if (!soff) {
     return(1);
   }
   if (n) {
     if (gvp == (char*)G__PVOID) {
       delete[] (vector<ClamLib::RootLayerDescription,allocator<ClamLib::RootLayerDescription> >*) soff;
     } else {
       G__setgvp((long) G__PVOID);
       for (int i = n - 1; i >= 0; --i) {
         ((vector<ClamLib::RootLayerDescription,allocator<ClamLib::RootLayerDescription> >*) (soff+(sizeof(vector<ClamLib::RootLayerDescription,allocator<ClamLib::RootLayerDescription> >)*i)))->~G__TvectorlEClamLibcLcLRootLayerDescriptioncOallocatorlEClamLibcLcLRootLayerDescriptiongRsPgR();
       }
       G__setgvp((long)gvp);
     }
   } else {
     if (gvp == (char*)G__PVOID) {
       delete (vector<ClamLib::RootLayerDescription,allocator<ClamLib::RootLayerDescription> >*) soff;
     } else {
       G__setgvp((long) G__PVOID);
       ((vector<ClamLib::RootLayerDescription,allocator<ClamLib::RootLayerDescription> >*) (soff))->~G__TvectorlEClamLibcLcLRootLayerDescriptioncOallocatorlEClamLibcLcLRootLayerDescriptiongRsPgR();
       G__setgvp((long)gvp);
     }
   }
   G__setnull(result7);
   return(1 || funcname || hash || result7 || libp) ;
}


/* Setting up global function */

/*********************************************************
* Member function Stub
*********************************************************/

/* ClamLib::RootLayerDescription */

/* vector<ClamLib::RootLayerDescription,allocator<ClamLib::RootLayerDescription> > */

/*********************************************************
* Global function Stub
*********************************************************/

/*********************************************************
* Get size of pointer to member function
*********************************************************/
class G__Sizep2memfuncdict {
 public:
  G__Sizep2memfuncdict(): p(&G__Sizep2memfuncdict::sizep2memfunc) {}
    size_t sizep2memfunc() { return(sizeof(p)); }
  private:
    size_t (G__Sizep2memfuncdict::*p)();
};

size_t G__get_sizep2memfuncdict()
{
  G__Sizep2memfuncdict a;
  G__setsizep2memfunc((int)a.sizep2memfunc());
  return((size_t)a.sizep2memfunc());
}


/*********************************************************
* virtual base class offset calculation interface
*********************************************************/

   /* Setting up class inheritance */

/*********************************************************
* Inheritance information setup/
*********************************************************/
extern "C" void G__cpp_setup_inheritancedict() {

   /* Setting up class inheritance */
   if(0==G__getnumbaseclass(G__get_linked_tagnum(&G__dictLN_ClamLibcLcLRootLayerDescription))) {
     ClamLib::RootLayerDescription *G__Lderived;
     G__Lderived=(ClamLib::RootLayerDescription*)0x1000;
     {
       TNamed *G__Lpbase=(TNamed*)G__Lderived;
       G__inheritance_setup(G__get_linked_tagnum(&G__dictLN_ClamLibcLcLRootLayerDescription),G__get_linked_tagnum(&G__dictLN_TNamed),(long)G__Lpbase-(long)G__Lderived,1,1);
     }
     {
       TObject *G__Lpbase=(TObject*)G__Lderived;
       G__inheritance_setup(G__get_linked_tagnum(&G__dictLN_ClamLibcLcLRootLayerDescription),G__get_linked_tagnum(&G__dictLN_TObject),(long)G__Lpbase-(long)G__Lderived,1,0);
     }
   }
}

/*********************************************************
* typedef information setup/
*********************************************************/
extern "C" void G__cpp_setup_typetabledict() {

   /* Setting up typedef entry */
   G__search_typename2("Version_t",115,-1,0,-1);
   G__setnewtype(-1,"Class version identifier (short)",0);
   G__search_typename2("vector<ROOT::TSchemaHelper>",117,G__get_linked_tagnum(&G__dictLN_vectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("_Ranit<ROOT::TSchemaHelper,difference_type,const_pointer,const_reference>",117,G__get_linked_tagnum(&G__dictLN__RanitlEROOTcLcLTSchemaHelpercOlongcOROOTcLcLTSchemaHelpermUcOROOTcLcLTSchemaHelperaNgR),0,G__get_linked_tagnum(&G__dictLN_vectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgR));
   G__setnewtype(-1,NULL,0);
   G__search_typename2("vector<ROOT::TSchemaHelper>",117,G__get_linked_tagnum(&G__dictLN_vectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("reverse_iterator<iterator>",117,G__get_linked_tagnum(&G__dictLN_reverse_iteratorlEvectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgRcLcLiteratorgR),0,G__get_linked_tagnum(&G__dictLN_vectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgR));
   G__setnewtype(-1,NULL,0);
   G__search_typename2("iterator<iterator_traits<vector<ROOT::TSchemaHelper,allocator<ROOT::TSchemaHelper> >::iterator>::iterator_category,iterator_traits<vector<ROOT::TSchemaHelper,allocator<ROOT::TSchemaHelper> >::iterator>::value_type,iterator_traits<vector<ROOT::TSchemaHelper,allocator<ROOT::TSchemaHelper> >::iterator>::difference_type,iterator_traits<vector<ROOT::TSchemaHelper,allocator<ROOT::TSchemaHelper> >::iterator>::pointer,iterator_traits<vector<ROOT::TSchemaHelper,allocator<ROOT::TSchemaHelper> >::iterator>::reference>",117,G__get_linked_tagnum(&G__dictLN_iteratorlErandom_access_iterator_tagcOROOTcLcLTSchemaHelpercOlongcOROOTcLcLTSchemaHelpermUcOROOTcLcLTSchemaHelperaNgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("iterator<random_access_iterator_tag,ROOT::TSchemaHelper>",117,G__get_linked_tagnum(&G__dictLN_iteratorlErandom_access_iterator_tagcOROOTcLcLTSchemaHelpercOlongcOROOTcLcLTSchemaHelpermUcOROOTcLcLTSchemaHelperaNgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("iterator<random_access_iterator_tag,ROOT::TSchemaHelper,long>",117,G__get_linked_tagnum(&G__dictLN_iteratorlErandom_access_iterator_tagcOROOTcLcLTSchemaHelpercOlongcOROOTcLcLTSchemaHelpermUcOROOTcLcLTSchemaHelperaNgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("iterator<random_access_iterator_tag,ROOT::TSchemaHelper,long,ROOT::TSchemaHelper*>",117,G__get_linked_tagnum(&G__dictLN_iteratorlErandom_access_iterator_tagcOROOTcLcLTSchemaHelpercOlongcOROOTcLcLTSchemaHelpermUcOROOTcLcLTSchemaHelperaNgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("reverse_iterator<const_iterator>",117,G__get_linked_tagnum(&G__dictLN_reverse_iteratorlEvectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgRcLcLconst_iteratorgR),0,G__get_linked_tagnum(&G__dictLN_vectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgR));
   G__setnewtype(-1,NULL,0);
   G__search_typename2("iterator<iterator_traits<vector<ROOT::TSchemaHelper,allocator<ROOT::TSchemaHelper> >::const_iterator>::iterator_category,iterator_traits<vector<ROOT::TSchemaHelper,allocator<ROOT::TSchemaHelper> >::const_iterator>::value_type,iterator_traits<vector<ROOT::TSchemaHelper,allocator<ROOT::TSchemaHelper> >::const_iterator>::difference_type,iterator_traits<vector<ROOT::TSchemaHelper,allocator<ROOT::TSchemaHelper> >::const_iterator>::pointer,iterator_traits<vector<ROOT::TSchemaHelper,allocator<ROOT::TSchemaHelper> >::const_iterator>::reference>",117,G__get_linked_tagnum(&G__dictLN_iteratorlErandom_access_iterator_tagcOROOTcLcLTSchemaHelpercOlongcOROOTcLcLTSchemaHelpermUcOROOTcLcLTSchemaHelperaNgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("vector<TVirtualArray*>",117,G__get_linked_tagnum(&G__dictLN_vectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("_Ranit<TVirtualArray*,difference_type,const_pointer,const_reference>",117,G__get_linked_tagnum(&G__dictLN__RanitlETVirtualArraymUcOlongcOTVirtualArraymUmUcOTVirtualArraymUaNgR),0,G__get_linked_tagnum(&G__dictLN_vectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgR));
   G__setnewtype(-1,NULL,0);
   G__search_typename2("vector<TVirtualArray*>",117,G__get_linked_tagnum(&G__dictLN_vectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("reverse_iterator<iterator>",117,G__get_linked_tagnum(&G__dictLN_reverse_iteratorlEvectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgRcLcLiteratorgR),0,G__get_linked_tagnum(&G__dictLN_vectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgR));
   G__setnewtype(-1,NULL,0);
   G__search_typename2("iterator<iterator_traits<vector<TVirtualArray*,allocator<TVirtualArray*> >::iterator>::iterator_category,iterator_traits<vector<TVirtualArray*,allocator<TVirtualArray*> >::iterator>::value_type,iterator_traits<vector<TVirtualArray*,allocator<TVirtualArray*> >::iterator>::difference_type,iterator_traits<vector<TVirtualArray*,allocator<TVirtualArray*> >::iterator>::pointer,iterator_traits<vector<TVirtualArray*,allocator<TVirtualArray*> >::iterator>::reference>",117,G__get_linked_tagnum(&G__dictLN_iteratorlErandom_access_iterator_tagcOTVirtualArraymUcOlongcOTVirtualArraymUmUcOTVirtualArraymUaNgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("iterator<random_access_iterator_tag,TVirtualArray*>",117,G__get_linked_tagnum(&G__dictLN_iteratorlErandom_access_iterator_tagcOTVirtualArraymUcOlongcOTVirtualArraymUmUcOTVirtualArraymUaNgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("iterator<random_access_iterator_tag,TVirtualArray*,long>",117,G__get_linked_tagnum(&G__dictLN_iteratorlErandom_access_iterator_tagcOTVirtualArraymUcOlongcOTVirtualArraymUmUcOTVirtualArraymUaNgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("iterator<random_access_iterator_tag,TVirtualArray*,long,TVirtualArray**>",117,G__get_linked_tagnum(&G__dictLN_iteratorlErandom_access_iterator_tagcOTVirtualArraymUcOlongcOTVirtualArraymUmUcOTVirtualArraymUaNgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("reverse_iterator<const_iterator>",117,G__get_linked_tagnum(&G__dictLN_reverse_iteratorlEvectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgRcLcLconst_iteratorgR),0,G__get_linked_tagnum(&G__dictLN_vectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgR));
   G__setnewtype(-1,NULL,0);
   G__search_typename2("iterator<iterator_traits<vector<TVirtualArray*,allocator<TVirtualArray*> >::const_iterator>::iterator_category,iterator_traits<vector<TVirtualArray*,allocator<TVirtualArray*> >::const_iterator>::value_type,iterator_traits<vector<TVirtualArray*,allocator<TVirtualArray*> >::const_iterator>::difference_type,iterator_traits<vector<TVirtualArray*,allocator<TVirtualArray*> >::const_iterator>::pointer,iterator_traits<vector<TVirtualArray*,allocator<TVirtualArray*> >::const_iterator>::reference>",117,G__get_linked_tagnum(&G__dictLN_iteratorlErandom_access_iterator_tagcOTVirtualArraymUcOlongcOTVirtualArraymUmUcOTVirtualArraymUaNgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("vector<ClamLib::RootLayerDescription>",117,G__get_linked_tagnum(&G__dictLN_vectorlEClamLibcLcLRootLayerDescriptioncOallocatorlEClamLibcLcLRootLayerDescriptiongRsPgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("value_type",117,G__get_linked_tagnum(&G__dictLN_ClamLibcLcLRootLayerDescription),0,G__get_linked_tagnum(&G__dictLN_vectorlEClamLibcLcLRootLayerDescriptioncOallocatorlEClamLibcLcLRootLayerDescriptiongRsPgR));
   G__setnewtype(-1,NULL,0);
   G__search_typename2("pointer",85,G__get_linked_tagnum(&G__dictLN_ClamLibcLcLRootLayerDescription),0,G__get_linked_tagnum(&G__dictLN_vectorlEClamLibcLcLRootLayerDescriptioncOallocatorlEClamLibcLcLRootLayerDescriptiongRsPgR));
   G__setnewtype(-1,NULL,0);
   G__search_typename2("const_pointer",85,G__get_linked_tagnum(&G__dictLN_ClamLibcLcLRootLayerDescription),0,G__get_linked_tagnum(&G__dictLN_vectorlEClamLibcLcLRootLayerDescriptioncOallocatorlEClamLibcLcLRootLayerDescriptiongRsPgR));
   G__setnewtype(-1,NULL,0);
   G__search_typename2("reference",117,G__get_linked_tagnum(&G__dictLN_ClamLibcLcLRootLayerDescription),1,G__get_linked_tagnum(&G__dictLN_vectorlEClamLibcLcLRootLayerDescriptioncOallocatorlEClamLibcLcLRootLayerDescriptiongRsPgR));
   G__setnewtype(-1,NULL,0);
   G__search_typename2("const_reference",117,G__get_linked_tagnum(&G__dictLN_ClamLibcLcLRootLayerDescription),1,G__get_linked_tagnum(&G__dictLN_vectorlEClamLibcLcLRootLayerDescriptioncOallocatorlEClamLibcLcLRootLayerDescriptiongRsPgR));
   G__setnewtype(-1,NULL,0);
   G__search_typename2("size_type",104,-1,0,G__get_linked_tagnum(&G__dictLN_vectorlEClamLibcLcLRootLayerDescriptioncOallocatorlEClamLibcLcLRootLayerDescriptiongRsPgR));
   G__setnewtype(-1,NULL,0);
   G__search_typename2("difference_type",108,-1,0,G__get_linked_tagnum(&G__dictLN_vectorlEClamLibcLcLRootLayerDescriptioncOallocatorlEClamLibcLcLRootLayerDescriptiongRsPgR));
   G__setnewtype(-1,NULL,0);
   G__search_typename2("_Ranit<ClamLib::RootLayerDescription,difference_type,const_pointer,const_reference>",117,G__get_linked_tagnum(&G__dictLN__RanitlEClamLibcLcLRootLayerDescriptioncOlongcOClamLibcLcLRootLayerDescriptionmUcOClamLibcLcLRootLayerDescriptionaNgR),0,G__get_linked_tagnum(&G__dictLN_vectorlEClamLibcLcLRootLayerDescriptioncOallocatorlEClamLibcLcLRootLayerDescriptiongRsPgR));
   G__setnewtype(-1,NULL,0);
   G__search_typename2("vector<ClamLib::RootLayerDescription>",117,G__get_linked_tagnum(&G__dictLN_vectorlEClamLibcLcLRootLayerDescriptioncOallocatorlEClamLibcLcLRootLayerDescriptiongRsPgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("reverse_iterator<iterator>",117,G__get_linked_tagnum(&G__dictLN_reverse_iteratorlEvectorlEClamLibcLcLRootLayerDescriptioncOallocatorlEClamLibcLcLRootLayerDescriptiongRsPgRcLcLiteratorgR),0,G__get_linked_tagnum(&G__dictLN_vectorlEClamLibcLcLRootLayerDescriptioncOallocatorlEClamLibcLcLRootLayerDescriptiongRsPgR));
   G__setnewtype(-1,NULL,0);
   G__search_typename2("iterator<iterator_traits<vector<ClamLib::RootLayerDescription,allocator<ClamLib::RootLayerDescription> >::iterator>::iterator_category,iterator_traits<vector<ClamLib::RootLayerDescription,allocator<ClamLib::RootLayerDescription> >::iterator>::value_type,iterator_traits<vector<ClamLib::RootLayerDescription,allocator<ClamLib::RootLayerDescription> >::iterator>::difference_type,iterator_traits<vector<ClamLib::RootLayerDescription,allocator<ClamLib::RootLayerDescription> >::iterator>::pointer,iterator_traits<vector<ClamLib::RootLayerDescription,allocator<ClamLib::RootLayerDescription> >::iterator>::reference>",117,G__get_linked_tagnum(&G__dictLN_iteratorlErandom_access_iterator_tagcOClamLibcLcLRootLayerDescriptioncOlongcOClamLibcLcLRootLayerDescriptionmUcOClamLibcLcLRootLayerDescriptionaNgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("iterator<random_access_iterator_tag,ClamLib::RootLayerDescription>",117,G__get_linked_tagnum(&G__dictLN_iteratorlErandom_access_iterator_tagcOClamLibcLcLRootLayerDescriptioncOlongcOClamLibcLcLRootLayerDescriptionmUcOClamLibcLcLRootLayerDescriptionaNgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("iterator<random_access_iterator_tag,ClamLib::RootLayerDescription,long>",117,G__get_linked_tagnum(&G__dictLN_iteratorlErandom_access_iterator_tagcOClamLibcLcLRootLayerDescriptioncOlongcOClamLibcLcLRootLayerDescriptionmUcOClamLibcLcLRootLayerDescriptionaNgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("iterator<random_access_iterator_tag,ClamLib::RootLayerDescription,long,ClamLib::RootLayerDescription*>",117,G__get_linked_tagnum(&G__dictLN_iteratorlErandom_access_iterator_tagcOClamLibcLcLRootLayerDescriptioncOlongcOClamLibcLcLRootLayerDescriptionmUcOClamLibcLcLRootLayerDescriptionaNgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("reverse_iterator",117,G__get_linked_tagnum(&G__dictLN_reverse_iteratorlEvectorlEClamLibcLcLRootLayerDescriptioncOallocatorlEClamLibcLcLRootLayerDescriptiongRsPgRcLcLiteratorgR),0,G__get_linked_tagnum(&G__dictLN_vectorlEClamLibcLcLRootLayerDescriptioncOallocatorlEClamLibcLcLRootLayerDescriptiongRsPgR));
   G__setnewtype(-1,NULL,0);
   G__search_typename2("reverse_iterator<const_iterator>",117,G__get_linked_tagnum(&G__dictLN_reverse_iteratorlEvectorlEClamLibcLcLRootLayerDescriptioncOallocatorlEClamLibcLcLRootLayerDescriptiongRsPgRcLcLconst_iteratorgR),0,G__get_linked_tagnum(&G__dictLN_vectorlEClamLibcLcLRootLayerDescriptioncOallocatorlEClamLibcLcLRootLayerDescriptiongRsPgR));
   G__setnewtype(-1,NULL,0);
   G__search_typename2("iterator<iterator_traits<vector<ClamLib::RootLayerDescription,allocator<ClamLib::RootLayerDescription> >::const_iterator>::iterator_category,iterator_traits<vector<ClamLib::RootLayerDescription,allocator<ClamLib::RootLayerDescription> >::const_iterator>::value_type,iterator_traits<vector<ClamLib::RootLayerDescription,allocator<ClamLib::RootLayerDescription> >::const_iterator>::difference_type,iterator_traits<vector<ClamLib::RootLayerDescription,allocator<ClamLib::RootLayerDescription> >::const_iterator>::pointer,iterator_traits<vector<ClamLib::RootLayerDescription,allocator<ClamLib::RootLayerDescription> >::const_iterator>::reference>",117,G__get_linked_tagnum(&G__dictLN_iteratorlErandom_access_iterator_tagcOClamLibcLcLRootLayerDescriptioncOlongcOClamLibcLcLRootLayerDescriptionmUcOClamLibcLcLRootLayerDescriptionaNgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("const_reverse_iterator",117,G__get_linked_tagnum(&G__dictLN_reverse_iteratorlEvectorlEClamLibcLcLRootLayerDescriptioncOallocatorlEClamLibcLcLRootLayerDescriptiongRsPgRcLcLconst_iteratorgR),0,G__get_linked_tagnum(&G__dictLN_vectorlEClamLibcLcLRootLayerDescriptioncOallocatorlEClamLibcLcLRootLayerDescriptiongRsPgR));
   G__setnewtype(-1,NULL,0);
}

/*********************************************************
* Data Member information setup/
*********************************************************/

   /* Setting up class,struct,union tag member variable */

   /* ClamLib::RootLayerDescription */
static void G__setup_memvarClamLibcLcLRootLayerDescription(void) {
   G__tag_memvar_setup(G__get_linked_tagnum(&G__dictLN_ClamLibcLcLRootLayerDescription));
   { ClamLib::RootLayerDescription *p; p=(ClamLib::RootLayerDescription*)0x1000; if (p) { }
   G__memvar_setup((void*)((long)(&p->_nr_x_pixels)-(long)(p)),104,0,0,-1,-1,-1,1,"_nr_x_pixels=",0,"*!< nr. neurons in x								*/");
   G__memvar_setup((void*)((long)(&p->_nr_y_pixels)-(long)(p)),104,0,0,-1,-1,-1,1,"_nr_y_pixels=",0,"*!< nr. neurons in y								*/");
   G__memvar_setup((void*)((long)(&p->_nr_features)-(long)(p)),104,0,0,-1,-1,-1,1,"_nr_features=",0,"*!< nr. of 'feature' or 'orientation' layers		*/");
   G__memvar_setup((void*)((long)(&p->_size_receptive_field_x)-(long)(p)),104,0,0,-1,-1,-1,1,"_size_receptive_field_x=",0,"*!< size of receptive field in x for this layer	*/	");
   G__memvar_setup((void*)((long)(&p->_size_receptive_field_y)-(long)(p)),104,0,0,-1,-1,-1,1,"_size_receptive_field_y=",0,"*!< size of receptive field in y for this layer	*/");
   G__memvar_setup((void*)((long)(&p->_nr_x_skips)-(long)(p)),104,0,0,-1,-1,-1,1,"_nr_x_skips=",0,"*!< nr. of 'skips' in x :must NOT be zero			*/");
   G__memvar_setup((void*)((long)(&p->_nr_y_skips)-(long)(p)),104,0,0,-1,-1,-1,1,"_nr_y_skips=",0,"/!< nr. of 'skips' in y : must NOT be zero		*/");
   G__memvar_setup((void*)0,85,0,0,G__get_linked_tagnum(&G__dictLN_TClass),-1,-2,4,"fgIsA=",0,(char*)NULL);
   }
   G__tag_memvar_reset();
}


   /* vector<ClamLib::RootLayerDescription,allocator<ClamLib::RootLayerDescription> > */
static void G__setup_memvarvectorlEClamLibcLcLRootLayerDescriptioncOallocatorlEClamLibcLcLRootLayerDescriptiongRsPgR(void) {
   G__tag_memvar_setup(G__get_linked_tagnum(&G__dictLN_vectorlEClamLibcLcLRootLayerDescriptioncOallocatorlEClamLibcLcLRootLayerDescriptiongRsPgR));
   { vector<ClamLib::RootLayerDescription,allocator<ClamLib::RootLayerDescription> > *p; p=(vector<ClamLib::RootLayerDescription,allocator<ClamLib::RootLayerDescription> >*)0x1000; if (p) { }
   }
   G__tag_memvar_reset();
}

extern "C" void G__cpp_setup_memvardict() {
}
/***********************************************************
************************************************************
************************************************************
************************************************************
************************************************************
************************************************************
************************************************************
***********************************************************/

/*********************************************************
* Member function information setup for each class
*********************************************************/
static void G__setup_memfuncClamLibcLcLRootLayerDescription(void) {
   /* ClamLib::RootLayerDescription */
   G__tag_memfunc_setup(G__get_linked_tagnum(&G__dictLN_ClamLibcLcLRootLayerDescription));
   G__memfunc_setup("RootLayerDescription",2085,G__dict_269_0_1, 105, G__get_linked_tagnum(&G__dictLN_ClamLibcLcLRootLayerDescription), -1, 0, 0, 1, 1, 0, "", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("Class",502,G__dict_269_0_2, 85, G__get_linked_tagnum(&G__dictLN_TClass), -1, 0, 0, 3, 1, 0, "", (char*)NULL, (void*) G__func2void( (TClass* (*)())(&ClamLib::RootLayerDescription::Class) ), 0);
   G__memfunc_setup("Class_Name",982,G__dict_269_0_3, 67, -1, -1, 0, 0, 3, 1, 1, "", (char*)NULL, (void*) G__func2void( (const char* (*)())(&ClamLib::RootLayerDescription::Class_Name) ), 0);
   G__memfunc_setup("Class_Version",1339,G__dict_269_0_4, 115, -1, G__defined_typename("Version_t"), 0, 0, 3, 1, 0, "", (char*)NULL, (void*) G__func2void( (Version_t (*)())(&ClamLib::RootLayerDescription::Class_Version) ), 0);
   G__memfunc_setup("Dictionary",1046,G__dict_269_0_5, 121, -1, -1, 0, 0, 3, 1, 0, "", (char*)NULL, (void*) G__func2void( (void (*)())(&ClamLib::RootLayerDescription::Dictionary) ), 0);
   G__memfunc_setup("IsA",253,(G__InterfaceMethod) NULL,85, G__get_linked_tagnum(&G__dictLN_TClass), -1, 0, 0, 1, 1, 8, "", (char*)NULL, (void*) NULL, 1);
   G__memfunc_setup("ShowMembers",1132,(G__InterfaceMethod) NULL,121, -1, -1, 0, 1, 1, 1, 0, "u 'TMemberInspector' - 1 - insp", (char*)NULL, (void*) NULL, 1);
   G__memfunc_setup("Streamer",835,(G__InterfaceMethod) NULL,121, -1, -1, 0, 1, 1, 1, 0, "u 'TBuffer' - 1 - b", (char*)NULL, (void*) NULL, 1);
   G__memfunc_setup("StreamerNVirtual",1656,G__dict_269_0_9, 121, -1, -1, 0, 1, 1, 1, 0, "u 'TBuffer' - 1 - b", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("DeclFileName",1145,G__dict_269_0_10, 67, -1, -1, 0, 0, 3, 1, 1, "", (char*)NULL, (void*) G__func2void( (const char* (*)())(&ClamLib::RootLayerDescription::DeclFileName) ), 0);
   G__memfunc_setup("ImplFileLine",1178,G__dict_269_0_11, 105, -1, -1, 0, 0, 3, 1, 0, "", (char*)NULL, (void*) G__func2void( (int (*)())(&ClamLib::RootLayerDescription::ImplFileLine) ), 0);
   G__memfunc_setup("ImplFileName",1171,G__dict_269_0_12, 67, -1, -1, 0, 0, 3, 1, 1, "", (char*)NULL, (void*) G__func2void( (const char* (*)())(&ClamLib::RootLayerDescription::ImplFileName) ), 0);
   G__memfunc_setup("DeclFileLine",1152,G__dict_269_0_13, 105, -1, -1, 0, 0, 3, 1, 0, "", (char*)NULL, (void*) G__func2void( (int (*)())(&ClamLib::RootLayerDescription::DeclFileLine) ), 0);
   // automatic copy constructor
   G__memfunc_setup("RootLayerDescription", 2085, G__dict_269_0_14, (int) ('i'), G__get_linked_tagnum(&G__dictLN_ClamLibcLcLRootLayerDescription), -1, 0, 1, 1, 1, 0, "u 'ClamLib::RootLayerDescription' - 11 - -", (char*) NULL, (void*) NULL, 0);
   // automatic destructor
   G__memfunc_setup("~RootLayerDescription", 2211, G__dict_269_0_15, (int) ('y'), -1, -1, 0, 0, 1, 1, 0, "", (char*) NULL, (void*) NULL, 0);
   // automatic assignment operator
   G__memfunc_setup("operator=", 937, G__dict_269_0_16, (int) ('u'), G__get_linked_tagnum(&G__dictLN_ClamLibcLcLRootLayerDescription), -1, 1, 1, 1, 1, 0, "u 'ClamLib::RootLayerDescription' - 11 - -", (char*) NULL, (void*) NULL, 0);
   G__tag_memfunc_reset();
}

static void G__setup_memfuncvectorlEClamLibcLcLRootLayerDescriptioncOallocatorlEClamLibcLcLRootLayerDescriptiongRsPgR(void) {
   /* vector<ClamLib::RootLayerDescription,allocator<ClamLib::RootLayerDescription> > */
   G__tag_memfunc_setup(G__get_linked_tagnum(&G__dictLN_vectorlEClamLibcLcLRootLayerDescriptioncOallocatorlEClamLibcLcLRootLayerDescriptiongRsPgR));
   G__memfunc_setup("at",213,G__dict_272_0_1, 117, G__get_linked_tagnum(&G__dictLN_ClamLibcLcLRootLayerDescription), -1, 1, 1, 1, 1, 0, "h - 'vector<ClamLib::RootLayerDescription,allocator<ClamLib::RootLayerDescription> >::size_type' 0 - n", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("begin",517,G__dict_272_0_2, 117, G__get_linked_tagnum(&G__dictLN_vectorlEClamLibcLcLRootLayerDescriptioncOallocatorlEClamLibcLcLRootLayerDescriptiongRsPgRcLcLiterator), -1, 0, 0, 1, 1, 0, "", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("end",311,G__dict_272_0_3, 117, G__get_linked_tagnum(&G__dictLN_vectorlEClamLibcLcLRootLayerDescriptioncOallocatorlEClamLibcLcLRootLayerDescriptiongRsPgRcLcLiterator), -1, 0, 0, 1, 1, 0, "", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("rbegin",631,G__dict_272_0_4, 117, G__get_linked_tagnum(&G__dictLN_reverse_iteratorlEvectorlEClamLibcLcLRootLayerDescriptioncOallocatorlEClamLibcLcLRootLayerDescriptiongRsPgRcLcLiteratorgR), G__defined_typename("vector<ClamLib::RootLayerDescription,allocator<ClamLib::RootLayerDescription> >::reverse_iterator"), 0, 0, 1, 1, 0, "", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("rend",425,G__dict_272_0_5, 117, G__get_linked_tagnum(&G__dictLN_reverse_iteratorlEvectorlEClamLibcLcLRootLayerDescriptioncOallocatorlEClamLibcLcLRootLayerDescriptiongRsPgRcLcLiteratorgR), G__defined_typename("vector<ClamLib::RootLayerDescription,allocator<ClamLib::RootLayerDescription> >::reverse_iterator"), 0, 0, 1, 1, 0, "", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("size",443,G__dict_272_0_6, 104, -1, G__defined_typename("vector<ClamLib::RootLayerDescription,allocator<ClamLib::RootLayerDescription> >::size_type"), 0, 0, 1, 1, 8, "", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("max_size",864,G__dict_272_0_7, 104, -1, G__defined_typename("vector<ClamLib::RootLayerDescription,allocator<ClamLib::RootLayerDescription> >::size_type"), 0, 0, 1, 1, 8, "", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("resize",658,G__dict_272_0_8, 121, -1, -1, 0, 1, 1, 1, 0, "h - 'vector<ClamLib::RootLayerDescription,allocator<ClamLib::RootLayerDescription> >::size_type' 0 - sz", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("resize",658,G__dict_272_0_9, 121, -1, -1, 0, 2, 1, 1, 0, 
"h - 'vector<ClamLib::RootLayerDescription,allocator<ClamLib::RootLayerDescription> >::size_type' 0 - sz u 'ClamLib::RootLayerDescription' - 0 - c", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("capacity",846,G__dict_272_0_10, 104, -1, G__defined_typename("vector<ClamLib::RootLayerDescription,allocator<ClamLib::RootLayerDescription> >::size_type"), 0, 0, 1, 1, 8, "", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("empty",559,G__dict_272_0_11, 103, -1, -1, 0, 0, 1, 1, 8, "", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("operator[]",1060,G__dict_272_0_12, 117, G__get_linked_tagnum(&G__dictLN_ClamLibcLcLRootLayerDescription), -1, 1, 1, 1, 1, 0, "h - 'vector<ClamLib::RootLayerDescription,allocator<ClamLib::RootLayerDescription> >::size_type' 0 - n", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("vector<ClamLib::RootLayerDescription,allocator<ClamLib::RootLayerDescription> >",7662,G__dict_272_0_13, 105, G__get_linked_tagnum(&G__dictLN_vectorlEClamLibcLcLRootLayerDescriptioncOallocatorlEClamLibcLcLRootLayerDescriptiongRsPgR), -1, 0, 0, 1, 1, 0, "", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("vector<ClamLib::RootLayerDescription,allocator<ClamLib::RootLayerDescription> >",7662,G__dict_272_0_14, 105, G__get_linked_tagnum(&G__dictLN_vectorlEClamLibcLcLRootLayerDescriptioncOallocatorlEClamLibcLcLRootLayerDescriptiongRsPgR), -1, 0, 2, 1, 1, 0, 
"h - 'vector<ClamLib::RootLayerDescription,allocator<ClamLib::RootLayerDescription> >::size_type' 0 - n u 'ClamLib::RootLayerDescription' - 11 'ClamLib::RootLayerDescription()' value", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("vector<ClamLib::RootLayerDescription,allocator<ClamLib::RootLayerDescription> >",7662,G__dict_272_0_15, 105, G__get_linked_tagnum(&G__dictLN_vectorlEClamLibcLcLRootLayerDescriptioncOallocatorlEClamLibcLcLRootLayerDescriptiongRsPgR), -1, 0, 1, 1, 1, 0, "u 'vector<ClamLib::RootLayerDescription,allocator<ClamLib::RootLayerDescription> >' - 11 - x", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("vector<ClamLib::RootLayerDescription,allocator<ClamLib::RootLayerDescription> >",7662,G__dict_272_0_16, 105, G__get_linked_tagnum(&G__dictLN_vectorlEClamLibcLcLRootLayerDescriptioncOallocatorlEClamLibcLcLRootLayerDescriptiongRsPgR), -1, 0, 2, 1, 1, 0, 
"u 'vector<ClamLib::RootLayerDescription,allocator<ClamLib::RootLayerDescription> >::const_iterator' - 0 - first u 'vector<ClamLib::RootLayerDescription,allocator<ClamLib::RootLayerDescription> >::const_iterator' - 0 - last", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("operator=",937,G__dict_272_0_17, 117, G__get_linked_tagnum(&G__dictLN_vectorlEClamLibcLcLRootLayerDescriptioncOallocatorlEClamLibcLcLRootLayerDescriptiongRsPgR), -1, 1, 1, 1, 1, 0, "u 'vector<ClamLib::RootLayerDescription,allocator<ClamLib::RootLayerDescription> >' - 11 - x", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("reserve",764,G__dict_272_0_18, 121, -1, -1, 0, 1, 1, 1, 0, "h - 'vector<ClamLib::RootLayerDescription,allocator<ClamLib::RootLayerDescription> >::size_type' 0 - n", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("front",553,G__dict_272_0_19, 117, G__get_linked_tagnum(&G__dictLN_ClamLibcLcLRootLayerDescription), -1, 1, 0, 1, 1, 0, "", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("back",401,G__dict_272_0_20, 117, G__get_linked_tagnum(&G__dictLN_ClamLibcLcLRootLayerDescription), -1, 1, 0, 1, 1, 0, "", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("push_back",944,G__dict_272_0_21, 121, -1, -1, 0, 1, 1, 1, 0, "u 'ClamLib::RootLayerDescription' - 11 - x", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("swap",443,G__dict_272_0_22, 121, -1, -1, 0, 1, 1, 1, 0, "u 'vector<ClamLib::RootLayerDescription,allocator<ClamLib::RootLayerDescription> >' - 1 - x", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("insert",661,G__dict_272_0_23, 117, G__get_linked_tagnum(&G__dictLN_vectorlEClamLibcLcLRootLayerDescriptioncOallocatorlEClamLibcLcLRootLayerDescriptiongRsPgRcLcLiterator), -1, 0, 2, 1, 1, 0, 
"u 'vector<ClamLib::RootLayerDescription,allocator<ClamLib::RootLayerDescription> >::iterator' - 0 - position u 'ClamLib::RootLayerDescription' - 11 - x", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("insert",661,G__dict_272_0_24, 121, -1, -1, 0, 3, 1, 1, 0, 
"u 'vector<ClamLib::RootLayerDescription,allocator<ClamLib::RootLayerDescription> >::iterator' - 0 - position u 'vector<ClamLib::RootLayerDescription,allocator<ClamLib::RootLayerDescription> >::const_iterator' - 0 - first "
"u 'vector<ClamLib::RootLayerDescription,allocator<ClamLib::RootLayerDescription> >::const_iterator' - 0 - last", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("insert",661,G__dict_272_0_25, 121, -1, -1, 0, 3, 1, 1, 0, 
"u 'vector<ClamLib::RootLayerDescription,allocator<ClamLib::RootLayerDescription> >::iterator' - 0 - position h - 'vector<ClamLib::RootLayerDescription,allocator<ClamLib::RootLayerDescription> >::size_type' 0 - n "
"u 'ClamLib::RootLayerDescription' - 11 - x", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("pop_back",831,G__dict_272_0_26, 121, -1, -1, 0, 0, 1, 1, 0, "", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("erase",528,G__dict_272_0_27, 121, -1, -1, 0, 1, 1, 1, 0, "u 'vector<ClamLib::RootLayerDescription,allocator<ClamLib::RootLayerDescription> >::iterator' - 0 - position", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("erase",528,G__dict_272_0_28, 121, -1, -1, 0, 2, 1, 1, 0, 
"u 'vector<ClamLib::RootLayerDescription,allocator<ClamLib::RootLayerDescription> >::iterator' - 0 - first u 'vector<ClamLib::RootLayerDescription,allocator<ClamLib::RootLayerDescription> >::iterator' - 0 - last", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("clear",519,G__dict_272_0_29, 121, -1, -1, 0, 0, 1, 1, 0, "", (char*)NULL, (void*) NULL, 0);
   // automatic destructor
   G__memfunc_setup("~vector<ClamLib::RootLayerDescription,allocator<ClamLib::RootLayerDescription> >", 7788, G__dict_272_0_30, (int) ('y'), -1, -1, 0, 0, 1, 1, 0, "", (char*) NULL, (void*) NULL, 0);
   G__tag_memfunc_reset();
}


/*********************************************************
* Member function information setup
*********************************************************/
extern "C" void G__cpp_setup_memfuncdict() {
}

/*********************************************************
* Global variable information setup for each class
*********************************************************/
static void G__cpp_setup_global0() {

   /* Setting up global variables */
   G__resetplocal();

}

static void G__cpp_setup_global1() {

   G__resetglobalenv();
}
extern "C" void G__cpp_setup_globaldict() {
  G__cpp_setup_global0();
  G__cpp_setup_global1();
}

/*********************************************************
* Global function information setup for each class
*********************************************************/
static void G__cpp_setup_func0() {
   G__lastifuncposition();

}

static void G__cpp_setup_func1() {
}

static void G__cpp_setup_func2() {
}

static void G__cpp_setup_func3() {
}

static void G__cpp_setup_func4() {

   G__resetifuncposition();
}

extern "C" void G__cpp_setup_funcdict() {
  G__cpp_setup_func0();
  G__cpp_setup_func1();
  G__cpp_setup_func2();
  G__cpp_setup_func3();
  G__cpp_setup_func4();
}

/*********************************************************
* Class,struct,union,enum tag information setup
*********************************************************/
/* Setup class/struct taginfo */
G__linked_taginfo G__dictLN_TClass = { "TClass" , 99 , -1 };
G__linked_taginfo G__dictLN_TBuffer = { "TBuffer" , 99 , -1 };
G__linked_taginfo G__dictLN_TMemberInspector = { "TMemberInspector" , 99 , -1 };
G__linked_taginfo G__dictLN_TObject = { "TObject" , 99 , -1 };
G__linked_taginfo G__dictLN_TNamed = { "TNamed" , 99 , -1 };
G__linked_taginfo G__dictLN_vectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgR = { "vector<ROOT::TSchemaHelper,allocator<ROOT::TSchemaHelper> >" , 99 , -1 };
G__linked_taginfo G__dictLN__RanitlEROOTcLcLTSchemaHelpercOlongcOROOTcLcLTSchemaHelpermUcOROOTcLcLTSchemaHelperaNgR = { "_Ranit<ROOT::TSchemaHelper,long,ROOT::TSchemaHelper*,ROOT::TSchemaHelper&>" , 115 , -1 };
G__linked_taginfo G__dictLN_iteratorlErandom_access_iterator_tagcOROOTcLcLTSchemaHelpercOlongcOROOTcLcLTSchemaHelpermUcOROOTcLcLTSchemaHelperaNgR = { "iterator<random_access_iterator_tag,ROOT::TSchemaHelper,long,ROOT::TSchemaHelper*,ROOT::TSchemaHelper&>" , 115 , -1 };
G__linked_taginfo G__dictLN_reverse_iteratorlEvectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgRcLcLiteratorgR = { "reverse_iterator<vector<ROOT::TSchemaHelper,allocator<ROOT::TSchemaHelper> >::iterator>" , 99 , -1 };
G__linked_taginfo G__dictLN_reverse_iteratorlEvectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgRcLcLconst_iteratorgR = { "reverse_iterator<vector<ROOT::TSchemaHelper,allocator<ROOT::TSchemaHelper> >::const_iterator>" , 99 , -1 };
G__linked_taginfo G__dictLN_vectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgR = { "vector<TVirtualArray*,allocator<TVirtualArray*> >" , 99 , -1 };
G__linked_taginfo G__dictLN__RanitlETVirtualArraymUcOlongcOTVirtualArraymUmUcOTVirtualArraymUaNgR = { "_Ranit<TVirtualArray*,long,TVirtualArray**,TVirtualArray*&>" , 115 , -1 };
G__linked_taginfo G__dictLN_iteratorlErandom_access_iterator_tagcOTVirtualArraymUcOlongcOTVirtualArraymUmUcOTVirtualArraymUaNgR = { "iterator<random_access_iterator_tag,TVirtualArray*,long,TVirtualArray**,TVirtualArray*&>" , 115 , -1 };
G__linked_taginfo G__dictLN_reverse_iteratorlEvectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgRcLcLiteratorgR = { "reverse_iterator<vector<TVirtualArray*,allocator<TVirtualArray*> >::iterator>" , 99 , -1 };
G__linked_taginfo G__dictLN_reverse_iteratorlEvectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgRcLcLconst_iteratorgR = { "reverse_iterator<vector<TVirtualArray*,allocator<TVirtualArray*> >::const_iterator>" , 99 , -1 };
G__linked_taginfo G__dictLN_ClamLib = { "ClamLib" , 110 , -1 };
G__linked_taginfo G__dictLN_ClamLibcLcLRootLayerDescription = { "ClamLib::RootLayerDescription" , 115 , -1 };
G__linked_taginfo G__dictLN_vectorlEClamLibcLcLRootLayerDescriptioncOallocatorlEClamLibcLcLRootLayerDescriptiongRsPgR = { "vector<ClamLib::RootLayerDescription,allocator<ClamLib::RootLayerDescription> >" , 99 , -1 };
G__linked_taginfo G__dictLN_vectorlEClamLibcLcLRootLayerDescriptioncOallocatorlEClamLibcLcLRootLayerDescriptiongRsPgRcLcLconst_iterator = { "vector<ClamLib::RootLayerDescription,allocator<ClamLib::RootLayerDescription> >::const_iterator" , 99 , -1 };
G__linked_taginfo G__dictLN__RanitlEClamLibcLcLRootLayerDescriptioncOlongcOClamLibcLcLRootLayerDescriptionmUcOClamLibcLcLRootLayerDescriptionaNgR = { "_Ranit<ClamLib::RootLayerDescription,long,ClamLib::RootLayerDescription*,ClamLib::RootLayerDescription&>" , 115 , -1 };
G__linked_taginfo G__dictLN_iteratorlErandom_access_iterator_tagcOClamLibcLcLRootLayerDescriptioncOlongcOClamLibcLcLRootLayerDescriptionmUcOClamLibcLcLRootLayerDescriptionaNgR = { "iterator<random_access_iterator_tag,ClamLib::RootLayerDescription,long,ClamLib::RootLayerDescription*,ClamLib::RootLayerDescription&>" , 115 , -1 };
G__linked_taginfo G__dictLN_vectorlEClamLibcLcLRootLayerDescriptioncOallocatorlEClamLibcLcLRootLayerDescriptiongRsPgRcLcLiterator = { "vector<ClamLib::RootLayerDescription,allocator<ClamLib::RootLayerDescription> >::iterator" , 99 , -1 };
G__linked_taginfo G__dictLN_reverse_iteratorlEvectorlEClamLibcLcLRootLayerDescriptioncOallocatorlEClamLibcLcLRootLayerDescriptiongRsPgRcLcLiteratorgR = { "reverse_iterator<vector<ClamLib::RootLayerDescription,allocator<ClamLib::RootLayerDescription> >::iterator>" , 99 , -1 };
G__linked_taginfo G__dictLN_reverse_iteratorlEvectorlEClamLibcLcLRootLayerDescriptioncOallocatorlEClamLibcLcLRootLayerDescriptiongRsPgRcLcLconst_iteratorgR = { "reverse_iterator<vector<ClamLib::RootLayerDescription,allocator<ClamLib::RootLayerDescription> >::const_iterator>" , 99 , -1 };

/* Reset class/struct taginfo */
extern "C" void G__cpp_reset_tagtabledict() {
  G__dictLN_TClass.tagnum = -1 ;
  G__dictLN_TBuffer.tagnum = -1 ;
  G__dictLN_TMemberInspector.tagnum = -1 ;
  G__dictLN_TObject.tagnum = -1 ;
  G__dictLN_TNamed.tagnum = -1 ;
  G__dictLN_vectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgR.tagnum = -1 ;
  G__dictLN__RanitlEROOTcLcLTSchemaHelpercOlongcOROOTcLcLTSchemaHelpermUcOROOTcLcLTSchemaHelperaNgR.tagnum = -1 ;
  G__dictLN_iteratorlErandom_access_iterator_tagcOROOTcLcLTSchemaHelpercOlongcOROOTcLcLTSchemaHelpermUcOROOTcLcLTSchemaHelperaNgR.tagnum = -1 ;
  G__dictLN_reverse_iteratorlEvectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgRcLcLiteratorgR.tagnum = -1 ;
  G__dictLN_reverse_iteratorlEvectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgRcLcLconst_iteratorgR.tagnum = -1 ;
  G__dictLN_vectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgR.tagnum = -1 ;
  G__dictLN__RanitlETVirtualArraymUcOlongcOTVirtualArraymUmUcOTVirtualArraymUaNgR.tagnum = -1 ;
  G__dictLN_iteratorlErandom_access_iterator_tagcOTVirtualArraymUcOlongcOTVirtualArraymUmUcOTVirtualArraymUaNgR.tagnum = -1 ;
  G__dictLN_reverse_iteratorlEvectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgRcLcLiteratorgR.tagnum = -1 ;
  G__dictLN_reverse_iteratorlEvectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgRcLcLconst_iteratorgR.tagnum = -1 ;
  G__dictLN_ClamLib.tagnum = -1 ;
  G__dictLN_ClamLibcLcLRootLayerDescription.tagnum = -1 ;
  G__dictLN_vectorlEClamLibcLcLRootLayerDescriptioncOallocatorlEClamLibcLcLRootLayerDescriptiongRsPgR.tagnum = -1 ;
  G__dictLN_vectorlEClamLibcLcLRootLayerDescriptioncOallocatorlEClamLibcLcLRootLayerDescriptiongRsPgRcLcLconst_iterator.tagnum = -1 ;
  G__dictLN__RanitlEClamLibcLcLRootLayerDescriptioncOlongcOClamLibcLcLRootLayerDescriptionmUcOClamLibcLcLRootLayerDescriptionaNgR.tagnum = -1 ;
  G__dictLN_iteratorlErandom_access_iterator_tagcOClamLibcLcLRootLayerDescriptioncOlongcOClamLibcLcLRootLayerDescriptionmUcOClamLibcLcLRootLayerDescriptionaNgR.tagnum = -1 ;
  G__dictLN_vectorlEClamLibcLcLRootLayerDescriptioncOallocatorlEClamLibcLcLRootLayerDescriptiongRsPgRcLcLiterator.tagnum = -1 ;
  G__dictLN_reverse_iteratorlEvectorlEClamLibcLcLRootLayerDescriptioncOallocatorlEClamLibcLcLRootLayerDescriptiongRsPgRcLcLiteratorgR.tagnum = -1 ;
  G__dictLN_reverse_iteratorlEvectorlEClamLibcLcLRootLayerDescriptioncOallocatorlEClamLibcLcLRootLayerDescriptiongRsPgRcLcLconst_iteratorgR.tagnum = -1 ;
}


extern "C" void G__cpp_setup_tagtabledict() {

   /* Setting up class,struct,union tag entry */
   G__get_linked_tagnum_fwd(&G__dictLN_TClass);
   G__get_linked_tagnum_fwd(&G__dictLN_TBuffer);
   G__get_linked_tagnum_fwd(&G__dictLN_TMemberInspector);
   G__get_linked_tagnum_fwd(&G__dictLN_TObject);
   G__get_linked_tagnum_fwd(&G__dictLN_TNamed);
   G__get_linked_tagnum_fwd(&G__dictLN_vectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgR);
   G__get_linked_tagnum_fwd(&G__dictLN__RanitlEROOTcLcLTSchemaHelpercOlongcOROOTcLcLTSchemaHelpermUcOROOTcLcLTSchemaHelperaNgR);
   G__get_linked_tagnum_fwd(&G__dictLN_iteratorlErandom_access_iterator_tagcOROOTcLcLTSchemaHelpercOlongcOROOTcLcLTSchemaHelpermUcOROOTcLcLTSchemaHelperaNgR);
   G__get_linked_tagnum_fwd(&G__dictLN_reverse_iteratorlEvectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgRcLcLiteratorgR);
   G__get_linked_tagnum_fwd(&G__dictLN_reverse_iteratorlEvectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgRcLcLconst_iteratorgR);
   G__get_linked_tagnum_fwd(&G__dictLN_vectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgR);
   G__get_linked_tagnum_fwd(&G__dictLN__RanitlETVirtualArraymUcOlongcOTVirtualArraymUmUcOTVirtualArraymUaNgR);
   G__get_linked_tagnum_fwd(&G__dictLN_iteratorlErandom_access_iterator_tagcOTVirtualArraymUcOlongcOTVirtualArraymUmUcOTVirtualArraymUaNgR);
   G__get_linked_tagnum_fwd(&G__dictLN_reverse_iteratorlEvectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgRcLcLiteratorgR);
   G__get_linked_tagnum_fwd(&G__dictLN_reverse_iteratorlEvectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgRcLcLconst_iteratorgR);
   G__get_linked_tagnum_fwd(&G__dictLN_ClamLib);
   G__tagtable_setup(G__get_linked_tagnum_fwd(&G__dictLN_ClamLibcLcLRootLayerDescription),sizeof(ClamLib::RootLayerDescription),-1,323840,(char*)NULL,G__setup_memvarClamLibcLcLRootLayerDescription,G__setup_memfuncClamLibcLcLRootLayerDescription);
   G__tagtable_setup(G__get_linked_tagnum_fwd(&G__dictLN_vectorlEClamLibcLcLRootLayerDescriptioncOallocatorlEClamLibcLcLRootLayerDescriptiongRsPgR),sizeof(vector<ClamLib::RootLayerDescription,allocator<ClamLib::RootLayerDescription> >),-1,298752,(char*)NULL,G__setup_memvarvectorlEClamLibcLcLRootLayerDescriptioncOallocatorlEClamLibcLcLRootLayerDescriptiongRsPgR,G__setup_memfuncvectorlEClamLibcLcLRootLayerDescriptioncOallocatorlEClamLibcLcLRootLayerDescriptiongRsPgR);
   G__get_linked_tagnum_fwd(&G__dictLN_vectorlEClamLibcLcLRootLayerDescriptioncOallocatorlEClamLibcLcLRootLayerDescriptiongRsPgRcLcLconst_iterator);
   G__get_linked_tagnum_fwd(&G__dictLN__RanitlEClamLibcLcLRootLayerDescriptioncOlongcOClamLibcLcLRootLayerDescriptionmUcOClamLibcLcLRootLayerDescriptionaNgR);
   G__get_linked_tagnum_fwd(&G__dictLN_iteratorlErandom_access_iterator_tagcOClamLibcLcLRootLayerDescriptioncOlongcOClamLibcLcLRootLayerDescriptionmUcOClamLibcLcLRootLayerDescriptionaNgR);
   G__get_linked_tagnum_fwd(&G__dictLN_vectorlEClamLibcLcLRootLayerDescriptioncOallocatorlEClamLibcLcLRootLayerDescriptiongRsPgRcLcLiterator);
   G__get_linked_tagnum_fwd(&G__dictLN_reverse_iteratorlEvectorlEClamLibcLcLRootLayerDescriptioncOallocatorlEClamLibcLcLRootLayerDescriptiongRsPgRcLcLiteratorgR);
   G__get_linked_tagnum_fwd(&G__dictLN_reverse_iteratorlEvectorlEClamLibcLcLRootLayerDescriptioncOallocatorlEClamLibcLcLRootLayerDescriptiongRsPgRcLcLconst_iteratorgR);
}
extern "C" void G__cpp_setupdict(void) {
  G__check_setup_version(30051515,"G__cpp_setupdict()");
  G__set_cpp_environmentdict();
  G__cpp_setup_tagtabledict();

  G__cpp_setup_inheritancedict();

  G__cpp_setup_typetabledict();

  G__cpp_setup_memvardict();

  G__cpp_setup_memfuncdict();
  G__cpp_setup_globaldict();
  G__cpp_setup_funcdict();

   if(0==G__getsizep2memfunc()) G__get_sizep2memfuncdict();
  return;
}
class G__cpp_setup_initdict {
  public:
    G__cpp_setup_initdict() { G__add_setup_func("dict",(G__incsetup)(&G__cpp_setupdict)); G__call_setup_funcs(); }
   ~G__cpp_setup_initdict() { G__remove_setup_func("dict"); }
};
G__cpp_setup_initdict G__cpp_setup_initializerdict;

